<?php

namespace Drupal\enum\Entity;

use Drupal\Core\Config\Entity\ConfigEntityBase;
use function array_column;
use function array_combine;
use function array_reduce;
use function is_null;

/**
 * Defines the Enum entity.
 *
 * @ConfigEntityType(
 *   id = "enum",
 *   label = @Translation("Enum"),
 *   handlers = {
 *     "view_builder" = "Drupal\Core\Entity\EntityViewBuilder",
 *     "list_builder" = "Drupal\enum\EnumListBuilder",
 *     "form" = {
 *       "add" = "Drupal\enum\Form\EnumForm",
 *       "edit" = "Drupal\enum\Form\EnumForm",
 *       "delete" = "Drupal\enum\Form\EnumDeleteForm"
 *     },
 *     "route_provider" = {
 *       "html" = "Drupal\enum\EnumHtmlRouteProvider",
 *     },
 *   },
 *   config_prefix = "enum",
 *   admin_permission = "administer site configuration",
 *   entity_keys = {
 *     "id" = "id",
 *     "label" = "label",
 *     "uuid" = "uuid"
 *   },
 *   links = {
 *     "canonical" = "/admin/structure/enum/{enum}",
 *     "add-form" = "/admin/structure/enum/add",
 *     "edit-form" = "/admin/structure/enum/{enum}/edit",
 *     "delete-form" = "/admin/structure/enum/{enum}/delete",
 *     "collection" = "/admin/structure/enum"
 *   },
 *   config_export = {
 *     "id",
 *     "label",
 *     "type",
 *     "group",
 *     "items"
 *   },
 *   lookup_keys = {
 *     "label",
 *     "type",
 *     "group",
 *   }
 * )
 */
class Enum extends ConfigEntityBase implements EnumInterface {

  /**
   * The Enum ID.
   *
   * @var string
   */
  protected $id;

  /**
   * The Enum label.
   *
   * @var string
   */
  protected $label;

  protected $type;

  protected $group;

  protected $items = [];

  public function getType() {
    return $this->type;
  }


  public function setType($type) {
    $this->type = $type;
  }

  public function getItems() {
    return empty($this->items) ? [] : $this->items;
  }

  public function getEnumLabels() {
    $options = [];
    foreach ($this->items as $item) {
      $options[$item['id']] = $item['label'];
    }
    return $options;
  }


  public function setItems($items) {
    $this->items = $items;
  }

  /**
   * @return mixed
   */
  public function getGroup() {
    return $this->group;
  }

  /**
   * @param mixed $group
   */
  public function setGroup($group): void {
    $this->group = $group;
  }

  public function save() {
    return parent::save(); // TODO: Change the autogenerated stub
  }

  protected function getNextId() {
    $max = array_reduce($this->items, function ($id, $item) {
      return $item['id'] > $id ? $item['id'] : $id;
    }, 0);
    return ++$max;
  }

  public function setItem($item) {
    $item['id'] = $this->getNextId();
    $this->items[$item['id']] = $item;
  }

  public function getEmptyItem() {
    return ['id' => '', 'label' => '', 'value'];
  }

  public function addItem($item) {
    $item['id'] = $this->getNextId();
    $this->setItem($item);
    return $item;
  }

}
